# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
      - cron:  '27 12 * * 1,3,5'
  workflow_dispatch:

name: R-CMD-check-examples

jobs:
  R-CMD-check-examples:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY_CODECOV }}
      AEMET_API_KEY01: ${{ secrets.AEMET_API_KEY }}
      AEMET_API_KEY02: ${{ secrets.AEMET_API_KEY_PKGDOWN }}
      AEMET_API_KEY03: ${{ secrets.AEMET_API_KEY2 }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2

